# Generated by Django 3.0.2 on 2020-02-11 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0018_course_course_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='track',
            name='track_cover',
            field=models.ImageField(blank=True, upload_to='profile'),
        ),
    ]
